### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by ponnamkarthik** [praveendath92/MDroid#93]
`FATAL EXCEPTION: main
                                                                    Process: in.co.praveenkumar, PID: 17725
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{in.co.praveenkumar/in.co.praveenkumar.mdroid.activity.LaunchActivity}: android.database.sqlite.SQLiteException: no such table: MOODLE_SITE_INFO (code 1): , while compiling: SELECT * FROM MOODLE_SITE_INFO WHERE id=? LIMIT 1
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                     Caused by: android.database.sqlite.SQLiteException: no such table: MOODLE_SITE_INFO (code 1): , while compiling: SELECT * FROM MOODLE_SITE_INFO WHERE id=? LIMIT 1
                                                                        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
                                                                        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
                                                                        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
                                                                        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1242)
                                                                        at com.orm.SugarRecord.find(SugarRecord.java:208)
                                                                        at com.orm.SugarRecord.findById(SugarRecord.java:138)
                                                                        at in.co.praveenkumar.mdroid.helper.SessionSetting.setCurrentValues(SessionSetting.java:62)
                                                                        at in.co.praveenkumar.mdroid.helper.SessionSetting.<init>(SessionSetting.java:43)
                                                                        at in.co.praveenkumar.mdroid.activity.LaunchActivity.onCreate(LaunchActivity.java:17)
                                                                        at android.app.Activity.performCreate(Activity.java:6679)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6126) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) `

I haven't changed any code

> https://github.com/praveendath92/MDroid/issues/87

there is no solution in this link

**Comment by vikaskumarg386** [comment]
@PonnamKarthik  have you got any solution for that ???
